// Code generated by ogen, DO NOT EDIT.

package chat

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIChatInternalClientPost implements POST /api/Chat/internal/client operation.
//
// Create a nw Client.
//
// POST /api/Chat/internal/client
func (UnimplementedHandler) APIChatInternalClientPost(ctx context.Context, req *APIChatInternalClientPostReqApplicationJSON) (r *APIChatInternalClientPostOKApplicationJSON, _ error) {
	return r, ht.ErrNotImplemented
}

// APIChatMuteDelete implements DELETE /api/Chat/mute operation.
//
// Create a new mute for an user.
//
// DELETE /api/Chat/mute
func (UnimplementedHandler) APIChatMuteDelete(ctx context.Context, req *APIChatMuteDeleteReqApplicationJSON) (r *APIChatMuteDeleteOKApplicationJSON, _ error) {
	return r, ht.ErrNotImplemented
}

// APIChatMutePost implements POST /api/Chat/mute operation.
//
// Create a new mute for an user.
//
// POST /api/Chat/mute
func (UnimplementedHandler) APIChatMutePost(ctx context.Context, req *APIChatMutePostReqApplicationJSON) (r *APIChatMutePostOKApplicationJSON, _ error) {
	return r, ht.ErrNotImplemented
}

// APIChatSendPost implements POST /api/Chat/send operation.
//
// Tracks a flip.
//
// POST /api/Chat/send
func (UnimplementedHandler) APIChatSendPost(ctx context.Context, req *APIChatSendPostReqApplicationJSON) (r *APIChatSendPostOKApplicationJSON, _ error) {
	return r, ht.ErrNotImplemented
}
